### ISSUE TITLE
Insufficient number of interrupts supported

### ISSUE THREAD

**Issue by ssumpf** [alex-ab/NOVA#8]
When the ioapic already consumes 120 gsi's, there are only a view left for MSIs. Also, a collision of MSI and GSI location is not reflected to user space.

**Comment by ssumpf** [comment]
@alex-ab: d5bf9de implements the test overlap checking and increases the GSI array from 128 to 192.

**Comment by alex-ab** [comment]
Thanks @ssumpf. Added to the next r10 branch and prepared a commit for Genode/staging.

**Comment by alex-ab** [comment]
Fixed on r10 branch.
